<a href="https://colab.research.google.com/github/argsprite/ProgramacionWebESBA/blob/main/caravanas_TRI_VS_DJIME.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Comparación de Contenido de Celdas (simulando 'CLOBs')

En un entorno de Colab/Python, 'CLOBs' (Character Large Objects) se manejarían como cadenas de texto (strings) que pueden ser muy largas. A continuación, definiremos dos variables de cadena en celdas separadas para simular tus 'celdas CLOB'.

In [1]:
# Celda 1: Definición de la primera 'CLOB'
clob_content_1 = """Este es el contenido de la primera celda. Puede ser un texto muy largo, como el contenido de un documento, un código fuente, o cualquier dato textual extenso. \nEste es un ejemplo de varias líneas para simular un CLOB."""

print("Contenido de CLOB 1 cargado.")

Contenido de CLOB 1 cargado.

In [2]:
# Celda 2: Definición de la segunda 'CLOB'
clob_content_2 = """Este es el contenido de la segunda celda. Vamos a hacerla ligeramente diferente para ver la comparación. \nEste es un ejemplo de varias líneas para simular un CLOB."""

print("Contenido de CLOB 2 cargado.")

Contenido de CLOB 2 cargado.

Ahora, vamos a comparar el contenido de ambas variables. Podemos hacer una comparación simple de igualdad o, para contenidos muy grandes y posibles diferencias sutiles, usar una biblioteca como `difflib` para obtener un resumen de las diferencias.

In [3]:
import difflib

# Comparación simple de igualdad
if clob_content_1 == clob_content_2:
    print("\nLas dos 'CLOBs' son idénticas.")
else:
    print("\nLas dos 'CLOBs' son diferentes.")

# Para una comparación más detallada, usando difflib
d = difflib.Differ()
diff = list(d.compare(clob_content_1.splitlines(), clob_content_2.splitlines()))

print("\n--- Diferencias detalladas (usando difflib) ---")
for line in diff:
    # Mostrar solo las líneas que son diferentes
    if line.startswith('+') or line.startswith('-') or line.startswith('?'):
        print(line)

print("---------------------------------------------")

Las dos 'CLOBs' son diferentes.

--- Diferencias detalladas (usando difflib) ---
- Este es el contenido de la primera celda. Puede ser un texto muy largo, como el contenido de un documento, un código fuente, o cualquier dato textual extenso.
+ Este es el contenido de la segunda celda. Vamos a hacerla ligeramente diferente para ver la comparación.
---------------------------------------------

In [6]:
# Instalar la librería 'xlrd' si no está instalada
!pip install xlrd

import pandas as pd

# Cargar el archivo, intentando primero como TSV (delimitado por tabulaciones), ya que el error sugería 'ID\tFECHA'
try:
    df_xls = pd.read_csv('/content/ltluizaga_2026.04.22_11.35.52.xls', sep='\t')
    print("Archivo cargado exitosamente como TSV.")
    display(df_xls.head())
except Exception as e_csv:
    print(f"Error al cargar el archivo como TSV: {e_csv}")
    print("Intentando cargar como XLS con xlrd (si es un archivo .xls válido)...")
    try:
        df_xls = pd.read_excel('/content/ltluizaga_2026.04.22_11.35.52.xls', engine='xlrd')
        print("Archivo cargado exitosamente como XLS.")
        display(df_xls.head())
    except Exception as e_xls:
        print(f"Error final al cargar el archivo como XLS: {e_xls}")
        print("Por favor, verifica el formato del archivo y su contenido.")

Requirement already satisfied: xlrd in /usr/local/lib/python3.12/dist-packages (2.0.2)
Archivo cargado exitosamente como TSV.

,ID,FECHAINSPECCION,FECHAEMISION,NROTRI,ENTIDAD_ID,ESPECIE_ID,CARAVANA,MOVIMIENTO_ID,OBSERVACIONES_VC,CARAVANARECIBIDAS,...,HAYCARAVANASUE,HAYEXCLUIDOUE,USERNAME,IMPRESIONANTERIOR,AVISOPREDESPACHO_ID,USUARIOANULACION,DESPACHOCUOTA481_ID,OBSERVACIONES,ESDJIME,Unnamed: 29
0,4650925,,17/02/25 13:02:13.381000,4650036,3120595,9,032050000776565 032050000776566 03205000077656...,28845650,,032050000776565 032050000776566 03205000077656...,...,1,0,20-22009721-9,17/02/25 13:04:27.624000,,,,,1,NaN

### Comparación de Contenido de Columnas 'CARAVANA' y 'CARAVANARECIBIDAS'

Vamos a extraer los valores de las columnas 'CARAVANA' y 'CARAVANARECIBIDAS' del primer registro de `df_xls` y compararlos usando `difflib` para ver las diferencias detalladas.

In [8]:
# Extraer el contenido de las columnas 'CARAVANA' y 'CARAVANARECIBIDAS' del primer registro
caravana_content = str(df_xls.loc[0, 'CARAVANA'])
caravana_recibidas_content = str(df_xls.loc[0, 'CARAVANARECIBIDAS'])

print(f"Contenido de 'CARAVANA' (primer registro):\n{caravana_content[:100]}...") # Mostrar solo una parte si es muy largo
print(f"Contenido de 'CARAVANARECIBIDAS' (primer registro):\n{caravana_recibidas_content[:100]}...") # Mostrar solo una parte si es muy largo

# Comparación simple de igualdad
if caravana_content == caravana_recibidas_content:
    print("\nLas columnas 'CARAVANA' y 'CARAVANARECIBIDAS' son idénticas en este registro.")
else:
    print("\nLas columnas 'CARAVANA' y 'CARAVANARECIBIDAS' son diferentes en este registro.")

# Para una comparación más detallada, usando difflib
import difflib
d = difflib.Differ()
diff_columns = list(d.compare(caravana_content.splitlines(), caravana_recibidas_content.splitlines()))

print("\n--- Diferencias detalladas entre 'CARAVANA' y 'CARAVANARECIBIDAS' (usando difflib) ---")
for line in diff_columns:
    # Mostrar solo las líneas que son diferentes
    if line.startswith('+') or line.startswith('-') or line.startswith('?'):
        print(line)

print("----------------------------------------------------------------------------------")

Contenido de 'CARAVANA' (primer registro):
032050000776565 032050000776566 032050000776567 032050000776568 032050000776570 032050000776574 0320...
Contenido de 'CARAVANARECIBIDAS' (primer registro):
032050000776565 032050000776566 032050000776568 032050000776570 032050000776574 032050000776576 0320...

Las columnas 'CARAVANA' y 'CARAVANARECIBIDAS' son diferentes en este registro.

--- Diferencias detalladas entre 'CARAVANA' y 'CARAVANARECIBIDAS' (usando difflib) ---
- 032050000776565 032050000776566 032050000776567 032050000776568 032050000776570 032050000776574 032050000776575 032050000776576 032050000776579 032050000997284 032050000997328 032050000997388 032050000997420 032050000997544 032050000997546 032050000997548 032050000997549 032050000997599 032050000997601 032050000997618 032050000997621 032050000997656 032050000997659 032050000997688 032050000997692 032050000997769 032050000997778 032050000998042 032050000998187 032050000998318 032050001133668 032050001133674
+ 032050000776565 032050000776566 032050000776568 032050000776570 032050000776574 032050000776576 032050000776579 032050000997284 032050000997328 032050000997388 032050000997420 032050000997548 032050000997549 032050000997601 032050000997618 032050000997621 032050000997656 032050000997659 032050000997688 032050000997692 032050000997769 032050000997778 032050000998042 032050000998187 032050000998318 032050001133668 032050001133674 032050000997782 032050001090051 032050001090000
----------------------------------------------------------------------------------

### Traducción de la lógica Qlik Sense a Python (Pandas)

Vamos a replicar los pasos de tu script de Qlik Sense para procesar las columnas 'CARAVANA' y 'CARAVANARECIBIDAS' del `df_xls`.

In [9]:
# 1. Dividir las caravanas en filas individuales para CARAVANA
caravanas_split = df_xls.assign(CARAVANAS_EN_COLUMNA=df_xls['CARAVANA'].str.split(' ')).explode('CARAVANAS_EN_COLUMNA')
caravanas_split = caravanas_split[caravanas_split['CARAVANAS_EN_COLUMNA'] != ''] # Eliminar entradas vacías si las hay

print("Primeras caravanas divididas de la columna 'CARAVANA':")
display(caravanas_split[['ID', 'CARAVANAS_EN_COLUMNA']].head())

Primeras caravanas divididas de la columna 'CARAVANA':

        ID CARAVANAS_EN_COLUMNA
0  4650925      032050000776565
0  4650925      032050000776566
0  4650925      032050000776567
0  4650925      032050000776568
0  4650925      032050000776570

In [10]:
# 2. Dividir las caravanas en filas individuales para CARAVANARECIBIDAS
recibidas_split = df_xls.assign(RECIBIDAS_EN_COLUMNA=df_xls['CARAVANARECIBIDAS'].str.split(' ')).explode('RECIBIDAS_EN_COLUMNA')
recibidas_split = recibidas_split[recibidas_split['RECIBIDAS_EN_COLUMNA'] != ''] # Eliminar entradas vacías si las hay

print("Primeras caravanas divididas de la columna 'CARAVANARECIBIDAS':")
display(recibidas_split[['ID', 'RECIBIDAS_EN_COLUMNA']].head())

Primeras caravanas divididas de la columna 'CARAVANARECIBIDAS':

        ID RECIBIDAS_EN_COLUMNA
0  4650925      032050000776565
0  4650925      032050000776566
0  4650925      032050000776568
0  4650925      032050000776570
0  4650925      032050000776574

In [11]:
# 3. Crear un conjunto (set) de caravanas recibidas para una búsqueda eficiente (equivalente a MAP_RECIBIDAS)
map_recibidas_set = set(recibidas_split['RECIBIDAS_EN_COLUMNA'].unique())

print(f"Número total de caravanas únicas recibidas: {len(map_recibidas_set)}")
# print(list(map_recibidas_set)[:10]) # Descomentar para ver las primeras 10 caravanas recibidas

Número total de caravanas únicas recibidas: 30

In [13]:
# 4. Identificar 'FALTANTES' y determinar el estado
# Creamos una copia para evitar SettingWithCopyWarning
faltantes_df = caravanas_split[['ID', 'CARAVANAS_EN_COLUMNA']].copy()
faltantes_df['estado'] = faltantes_df['CARAVANAS_EN_COLUMNA'].apply(lambda x: 'RECIBIDAS' if x in map_recibidas_set else 'NO RECIBIDAS')

print("Tabla resultante 'FALTANTES':")
display(faltantes_df.head(32))

Tabla resultante 'FALTANTES':

        ID CARAVANAS_EN_COLUMNA        estado
0  4650925      032050000776565     RECIBIDAS
0  4650925      032050000776566     RECIBIDAS
0  4650925      032050000776567  NO RECIBIDAS
0  4650925      032050000776568     RECIBIDAS
0  4650925      032050000776570     RECIBIDAS
0  4650925      032050000776574     RECIBIDAS
0  4650925      032050000776575  NO RECIBIDAS
0  4650925      032050000776576     RECIBIDAS
0  4650925      032050000776579     RECIBIDAS
0  4650925      032050000997284     RECIBIDAS
0  4650925      032050000997328     RECIBIDAS
0  4650925      032050000997388     RECIBIDAS
0  4650925      032050000997420     RECIBIDAS
0  4650925      032050000997544  NO RECIBIDAS
0  4650925      032050000997546  NO RECIBIDAS
0  4650925      032050000997548     RECIBIDAS
0  4650925      032050000997549     RECIBIDAS
0  4650925      032050000997599  NO RECIBIDAS
0  4650925      032050000997601     RECIBIDAS
0  4650925      032050000997618     RECIBIDAS
0  4650925      032050000997621     RECIBIDAS
0  4650925      032050000997656     RECIBIDAS
0  4650925      032050000997659     RECIBIDAS
0  4650925      032050000997688     RECIBIDAS
0  4650925      032050000997692     RECIBIDAS
0  4650925      032050000997769     RECIBIDAS
0  4650925      032050000997778     RECIBIDAS
0  4650925      032050000998042     RECIBIDAS
0  4650925      032050000998187     RECIBIDAS
0  4650925      032050000998318     RECIBIDAS
0  4650925      032050001133668     RECIBIDAS
0  4650925      032050001133674     RECIBIDAS

### Identificación de 'REEMPLAZADAS'

Para identificar las caravanas 'REEMPLAZADAS', buscaremos aquellas que están presentes en la columna `CARAVANARECIBIDAS` pero no en la columna `CARAVANA` original. Esto implica crear un conjunto de las caravanas originales y luego filtrar las recibidas.

In [14]:
# Crear un conjunto (set) de caravanas originales para una búsqueda eficiente
map_caravanas_set = set(caravanas_split['CARAVANAS_EN_COLUMNA'].unique())

# Identificar 'REEMPLAZADAS'
# Creamos una copia para evitar SettingWithCopyWarning
reemplazadas_df = recibidas_split[['ID', 'RECIBIDAS_EN_COLUMNA']].copy()
reemplazadas_df['estado'] = reemplazadas_df['RECIBIDAS_EN_COLUMNA'].apply(lambda x: 'REEMPLAZADA' if x not in map_caravanas_set else 'NO REEMPLAZADA')

# Mostrar solo las caravanas que fueron 'REEMPLAZADAS'
reemplazadas_filtrado_df = reemplazadas_df[reemplazadas_df['estado'] == 'REEMPLAZADA']

print("Caravanas 'REEMPLAZADAS' identificadas:")
display(reemplazadas_filtrado_df.head())

print(f"Número total de caravanas 'REEMPLAZADAS': {len(reemplazadas_filtrado_df)}")

Caravanas 'REEMPLAZADAS' identificadas:

        ID RECIBIDAS_EN_COLUMNA       estado
0  4650925      032050000997782  REEMPLAZADA
0  4650925      032050001090051  REEMPLAZADA
0  4650925      032050001090000  REEMPLAZADA

Número total de caravanas 'REEMPLAZADAS': 3

### Consolidación de 'NO RECIBIDAS' y 'REEMPLAZADAS'

Vamos a crear un único DataFrame que contenga tanto las caravanas identificadas como 'NO RECIBIDAS' como las 'REEMPLAZADAS'.

In [15]:
# Filtrar solo las caravanas 'NO RECIBIDAS'
no_recibidas_df = faltantes_df[faltantes_df['estado'] == 'NO RECIBIDAS'].copy()

# Renombrar la columna de caravanas en 'no_recibidas_df' para que coincida con 'reemplazadas_filtrado_df'
no_recibidas_df.rename(columns={'CARAVANAS_EN_COLUMNA': 'CARAVANA_AFECTADA'}, inplace=True)

# Renombrar la columna de caravanas en 'reemplazadas_filtrado_df'
reemplazadas_consolidado_df = reemplazadas_filtrado_df.rename(columns={'RECIBIDAS_EN_COLUMNA': 'CARAVANA_AFECTADA'}).copy()

# Combinar ambos DataFrames
df_consolidado_estados = pd.concat([no_recibidas_df, reemplazadas_consolidado_df], ignore_index=True)

print("DataFrame Consolidado de Estados (NO RECIBIDAS y REEMPLAZADAS):")
display(df_consolidado_estados)

DataFrame Consolidado de Estados (NO RECIBIDAS y REEMPLAZADAS):

        ID CARAVANA_AFECTADA        estado
0  4650925   032050000776567  NO RECIBIDAS
1  4650925   032050000776575  NO RECIBIDAS
2  4650925   032050000997544  NO RECIBIDAS
3  4650925   032050000997546  NO RECIBIDAS
4  4650925   032050000997599  NO RECIBIDAS
5  4650925   032050000997782   REEMPLAZADA
6  4650925   032050001090051   REEMPLAZADA
7  4650925   032050001090000   REEMPLAZADA

### Mostrar el contexto original de las Caravanas Afectadas

Para ver las listas completas de 'CARAVANA' y 'CARAVANARECIBIDAS' para cada `ID` que tiene caravanas 'NO RECIBIDAS' o 'REEMPLAZADAS', fusionaremos el DataFrame `df_consolidado_estados` con el `df_xls` original.

In [16]:
# Fusionar df_consolidado_estados con df_xls para obtener las columnas CARAVANA y CARAVANARECIBIDAS
df_final_contexto = pd.merge(
    df_consolidado_estados,
    df_xls[['ID', 'CARAVANA', 'CARAVANARECIBIDAS']],
    on='ID',
    how='left'
)

print("DataFrame consolidado con el contexto original de 'CARAVANA' y 'CARAVANARECIBIDAS':")
display(df_final_contexto[['ID', 'CARAVANA_AFECTADA', 'estado', 'CARAVANA', 'CARAVANARECIBIDAS']])

DataFrame consolidado con el contexto original de 'CARAVANA' y 'CARAVANARECIBIDAS':

,ID,CARAVANA_AFECTADA,estado,CARAVANA,CARAVANARECIBIDAS
0,4650925,032050000776567,NO RECIBIDAS,032050000776565 032050000776566 03205000077656...,032050000776565 032050000776566 03205000077656...
1,4650925,032050000776575,NO RECIBIDAS,032050000776565 032050000776566 03205000077656...,032050000776565 032050000776566 03205000077656...
2,4650925,032050000997544,NO RECIBIDAS,032050000776565 032050000776566 03205000077656...,032050000776565 032050000776566 03205000077656...
3,4650925,032050000997546,NO RECIBIDAS,032050000776565 032050000776566 03205000077656...,032050000776565 032050000776566 03205000077656...
4,4650925,032050000997599,NO RECIBIDAS,032050000776565 032050000776566 03205000077656...,032050000776565 032050000776566 03205000077656...
5,4650925,032050000997782,REEMPLAZADA,032050000776565 032050000776566 03205000077656...,032050000776565 032050000776566 03205000077656...
6,4650925,032050001090051,REEMPLAZADA,032050000776565 032050000776566 03205000077656...,032050000776565 032050000776566 03205000077656...
7,4650925,032050001090000,REEMPLAZADA,032050000776565 032050000776566 03205000077656...,032050000776565 032050000776566 03205000077656...

### Consolidado de todas las Caravanas con sus Estados Detallados

Aquí se presenta un DataFrame con todas las caravanas únicas que aparecieron en las columnas 'CARAVANA' o 'CARAVANARECIBIDAS', junto con dos columnas de estado:
- **Estado_Desde_Envio**: Indica si la caravana, que fue parte de la lista original 'CARAVANA', fue 'RECIBIDAS' o 'NO RECIBIDAS'. Si no estaba en la lista original, se marcará como 'NO ENVIADA'.
- **Estado_Desde_Recepcion**: Indica si la caravana, que fue parte de la lista de 'CARAVANARECIBIDAS', fue 'REEMPLAZADA' o 'NO REEMPLAZADA'. Si no estaba en la lista de recibidas, se marcará como 'NO RECIBIDA EN CONTEO'.

In [18]:
# 1. Preparar el DataFrame de las caravanas esperadas/enviadas
df_estado_enviado = faltantes_df[['ID', 'CARAVANAS_EN_COLUMNA', 'estado']].copy()
df_estado_enviado.rename(columns={'CARAVANAS_EN_COLUMNA': 'Caravana_ID', 'estado': 'Estado_Desde_Envio'}, inplace=True)

# 2. Preparar el DataFrame de las caravanas realmente recibidas
df_estado_recibido = reemplazadas_df[['ID', 'RECIBIDAS_EN_COLUMNA', 'estado']].copy()
df_estado_recibido.rename(columns={'RECIBIDAS_EN_COLUMNA': 'Caravana_ID', 'estado': 'Estado_Desde_Recepcion'}, inplace=True)

# 3. Combinar ambos DataFrames para obtener un listado único de todas las caravanas y sus estados
# Usamos un 'outer' merge para incluir todas las caravanas que aparecieron en cualquiera de las dos listas
df_caravanas_estados_consolidado = pd.merge(
    df_estado_enviado,
    df_estado_recibido,
    on=['ID', 'Caravana_ID'],
    how='outer'
)

# 4. Rellenar los valores NaN para clarificar si una caravana no estaba en una de las listas originales
# Por ejemplo, si una caravana solo aparece en 'CARAVANARECIBIDAS' y no en 'CARAVANA', su 'Estado_Desde_Envio' será NaN.
# Si una caravana solo aparece en 'CARAVANA' y no en 'CARAVANARECIBIDAS', su 'Estado_Desde_Recepcion' será NaN.
df_caravanas_estados_consolidado['Estado_Desde_Envio'].fillna('NO ENVIADA', inplace=True)
df_caravanas_estados_consolidado['Estado_Desde_Recepcion'].fillna('NO RECIBIDA EN CONTEO', inplace=True)


print("Consolidado de todas las caravanas con sus dos estados:")
display(df_caravanas_estados_consolidado.sort_values(by=['ID', 'Caravana_ID']))

Consolidado de todas las caravanas con sus dos estados:

/tmp/ipykernel_8484/3920579170.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_caravanas_estados_consolidado['Estado_Desde_Envio'].fillna('NO ENVIADA', inplace=True)
/tmp/ipykernel_8484/3920579170.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_caravanas_estados_consolidado['Estado_Desde_Recepcion'].fillna('NO RECIBIDA EN CONTEO', inplace=True)

         ID      Caravana_ID Estado_Desde_Envio Estado_Desde_Recepcion
0   4650925  032050000776565          RECIBIDAS         NO REEMPLAZADA
1   4650925  032050000776566          RECIBIDAS         NO REEMPLAZADA
2   4650925  032050000776567       NO RECIBIDAS  NO RECIBIDA EN CONTEO
3   4650925  032050000776568          RECIBIDAS         NO REEMPLAZADA
4   4650925  032050000776570          RECIBIDAS         NO REEMPLAZADA
5   4650925  032050000776574          RECIBIDAS         NO REEMPLAZADA
6   4650925  032050000776575       NO RECIBIDAS  NO RECIBIDA EN CONTEO
7   4650925  032050000776576          RECIBIDAS         NO REEMPLAZADA
8   4650925  032050000776579          RECIBIDAS         NO REEMPLAZADA
9   4650925  032050000997284          RECIBIDAS         NO REEMPLAZADA
10  4650925  032050000997328          RECIBIDAS         NO REEMPLAZADA
11  4650925  032050000997388          RECIBIDAS         NO REEMPLAZADA
12  4650925  032050000997420          RECIBIDAS         NO REEMPLAZADA
13  4650925  032050000997544       NO RECIBIDAS  NO RECIBIDA EN CONTEO
14  4650925  032050000997546       NO RECIBIDAS  NO RECIBIDA EN CONTEO
15  4650925  032050000997548          RECIBIDAS         NO REEMPLAZADA
16  4650925  032050000997549          RECIBIDAS         NO REEMPLAZADA
17  4650925  032050000997599       NO RECIBIDAS  NO RECIBIDA EN CONTEO
18  4650925  032050000997601          RECIBIDAS         NO REEMPLAZADA
19  4650925  032050000997618          RECIBIDAS         NO REEMPLAZADA
20  4650925  032050000997621          RECIBIDAS         NO REEMPLAZADA
21  4650925  032050000997656          RECIBIDAS         NO REEMPLAZADA
22  4650925  032050000997659          RECIBIDAS         NO REEMPLAZADA
23  4650925  032050000997688          RECIBIDAS         NO REEMPLAZADA
24  4650925  032050000997692          RECIBIDAS         NO REEMPLAZADA
25  4650925  032050000997769          RECIBIDAS         NO REEMPLAZADA
26  4650925  032050000997778          RECIBIDAS         NO REEMPLAZADA
27  4650925  032050000997782         NO ENVIADA            REEMPLAZADA
28  4650925  032050000998042          RECIBIDAS         NO REEMPLAZADA
29  4650925  032050000998187          RECIBIDAS         NO REEMPLAZADA
30  4650925  032050000998318          RECIBIDAS         NO REEMPLAZADA
31  4650925  032050001090000         NO ENVIADA            REEMPLAZADA
32  4650925  032050001090051         NO ENVIADA            REEMPLAZADA
33  4650925  032050001133668          RECIBIDAS         NO REEMPLAZADA
34  4650925  032050001133674          RECIBIDAS         NO REEMPLAZADA

In [28]:
df_caravanas_estados_consolidado['Estado_Desde_Envio'] = df_caravanas_estados_consolidado['Estado_Desde_Envio'].replace({'RECIBIDAS': 'ENVIADAS', 'NO RECIBIDAS': 'NO ENVIADAS'})

print("Valores en 'Estado_Desde_Envio' actualizados:")
display(df_caravanas_estados_consolidado['Estado_Desde_Envio'].value_counts())

Valores en 'Estado_Desde_Envio' actualizados:

Estado_Desde_Envio
ENVIADAS       27
NO ENVIADAS     5
NO ENVIADA      3
Name: count, dtype: int64

In [37]:
# 1. Dividir las caravanas en filas individuales para CARAVANA
caravanas_split = df_xls.assign(CARAVANAS_EN_COLUMNA=df_xls['CARAVANA'].str.split(' ')).explode('CARAVANAS_EN_COLUMNA')
caravanas_split = caravanas_split[caravanas_split['CARAVANAS_EN_COLUMNA'] != ''] # Eliminar entradas vacías si las hay

# 2. Dividir las caravanas en filas individuales para CARAVANARECIBIDAS
recibidas_split = df_xls.assign(RECIBIDAS_EN_COLUMNA=df_xls['CARAVANARECIBIDAS'].str.split(' ')).explode('RECIBIDAS_EN_COLUMNA')
recibidas_split = recibidas_split[recibidas_split['RECIBIDAS_EN_COLUMNA'] != ''] # Eliminar entradas vacías si las hay

# 3. Crear un conjunto (set) de caravanas recibidas para una búsqueda eficiente (equivalente a MAP_RECIBIDAS)
map_recibidas_set = set(recibidas_split['RECIBIDAS_EN_COLUMNA'].unique())

# 4. Identificar 'FALTANTES' y determinar el estado (esta sección ya no define el Estado_Desde_Envio final)
faltantes_df = caravanas_split[['ID', 'CARAVANAS_EN_COLUMNA']].copy()
faltantes_df['estado'] = faltantes_df['CARAVANAS_EN_COLUMNA'].apply(lambda x: 'RECIBIDAS' if x in map_recibidas_set else 'NO RECIBIDAS')

# 5. Crear un conjunto (set) de caravanas originales para una búsqueda eficiente
map_caravanas_set = set(caravanas_split['CARAVANAS_EN_COLUMNA'].unique())

# 6. Identificar 'REEMPLAZADAS'
reemplazadas_df = recibidas_split[['ID', 'RECIBIDAS_EN_COLUMNA']].copy()
reemplazadas_df['estado'] = reemplazadas_df['RECIBIDAS_EN_COLUMNA'].apply(lambda x: 'REEMPLAZADA' if x not in map_caravanas_set else 'NO REEMPLAZADA')

# 7. Filtrar solo las caravanas 'NO RECIBIDAS'
no_recibidas_df = faltantes_df[faltantes_df['estado'] == 'NO RECIBIDAS'].copy()
no_recibidas_df.rename(columns={'CARAVANAS_EN_COLUMNA': 'CARAVANA_AFECTADA'}, inplace=True)

# 8. Consolidar las 'REEMPLAZADAS'
reemplazadas_filtrado_df = reemplazadas_df[reemplazadas_df['estado'] == 'REEMPLAZADA']
reemplazadas_consolidado_df = reemplazadas_filtrado_df.rename(columns={'RECIBIDAS_EN_COLUMNA': 'CARAVANA_AFECTADA'}).copy()

# 9. Combinar los DataFrames de 'NO RECIBIDAS' y 'REEMPLAZADAS'
df_consolidado_estados = pd.concat([no_recibidas_df, reemplazadas_consolidado_df], ignore_index=True)

# 10. Fusionar con el df_xls original para contexto
df_final_contexto = pd.merge(
    df_consolidado_estados,
    df_xls[['ID', 'CARAVANA', 'CARAVANARECIBIDAS']],
    on='ID',
    how='left'
)

# 11. Preparar el DataFrame de las caravanas esperadas/enviadas
df_estado_enviado = caravanas_split[['ID', 'CARAVANAS_EN_COLUMNA']].copy()
df_estado_enviado.rename(columns={'CARAVANAS_EN_COLUMNA': 'Caravana_ID'}, inplace=True)
df_estado_enviado['Estado_Desde_Envio'] = 'ENVIADA' # Todas las caravanas en este DF fueron originalmente 'enviadas'

# 12. Preparar el DataFrame de las caravanas realmente recibidas
df_estado_recibido = reemplazadas_df[['ID', 'RECIBIDAS_EN_COLUMNA', 'estado']].copy()
df_estado_recibido.rename(columns={'RECIBIDAS_EN_COLUMNA': 'Caravana_ID', 'estado': 'Estado_Desde_Recepcion'}, inplace=True)

# 13. Combinar ambos DataFrames para obtener un listado único de todas las caravanas y sus estados
df_caravanas_estados_consolidado = pd.merge(
    df_estado_enviado,
    df_estado_recibido,
    on=['ID', 'Caravana_ID'],
    how='outer'
)

# 14. Rellenar los valores NaN para clarificar si una caravana no estaba en una de las listas originales
df_caravanas_estados_consolidado['Estado_Desde_Envio'] = df_caravanas_estados_consolidado['Estado_Desde_Envio'].fillna('NO ENVIADA')
df_caravanas_estados_consolidado['Estado_Desde_Recepcion'] = df_caravanas_estados_consolidado['Estado_Desde_Recepcion'].fillna('NO RECIBIDA') # Cambiado de 'NO RECIBIDA EN CONTEO'

# 15. Actualizar los términos de estado según lo solicitado (esta sección ya no es necesaria con la nueva lógica de Estado_Desde_Envio)
# df_caravanas_estados_consolidado['Estado_Desde_Envio'] = df_caravanas_estados_consolidado['Estado_Desde_Envio'].replace({'RECIBIDAS': 'ENVIADAS', 'NO RECIBIDAS': 'NO ENVIADAS'})

print("DataFrame consolidado final (primeros 50 registros):")
display(df_caravanas_estados_consolidado.sort_values(by=['ID', 'Caravana_ID']).head(50))

DataFrame consolidado final (primeros 50 registros):

         ID      Caravana_ID Estado_Desde_Envio Estado_Desde_Recepcion
0   4650925  032050000776565            ENVIADA         NO REEMPLAZADA
1   4650925  032050000776566            ENVIADA         NO REEMPLAZADA
2   4650925  032050000776567            ENVIADA            NO RECIBIDA
3   4650925  032050000776568            ENVIADA         NO REEMPLAZADA
4   4650925  032050000776570            ENVIADA         NO REEMPLAZADA
5   4650925  032050000776574            ENVIADA         NO REEMPLAZADA
6   4650925  032050000776575            ENVIADA            NO RECIBIDA
7   4650925  032050000776576            ENVIADA         NO REEMPLAZADA
8   4650925  032050000776579            ENVIADA         NO REEMPLAZADA
9   4650925  032050000997284            ENVIADA         NO REEMPLAZADA
10  4650925  032050000997328            ENVIADA         NO REEMPLAZADA
11  4650925  032050000997388            ENVIADA         NO REEMPLAZADA
12  4650925  032050000997420            ENVIADA         NO REEMPLAZADA
13  4650925  032050000997544            ENVIADA            NO RECIBIDA
14  4650925  032050000997546            ENVIADA            NO RECIBIDA
15  4650925  032050000997548            ENVIADA         NO REEMPLAZADA
16  4650925  032050000997549            ENVIADA         NO REEMPLAZADA
17  4650925  032050000997599            ENVIADA            NO RECIBIDA
18  4650925  032050000997601            ENVIADA         NO REEMPLAZADA
19  4650925  032050000997618            ENVIADA         NO REEMPLAZADA
20  4650925  032050000997621            ENVIADA         NO REEMPLAZADA
21  4650925  032050000997656            ENVIADA         NO REEMPLAZADA
22  4650925  032050000997659            ENVIADA         NO REEMPLAZADA
23  4650925  032050000997688            ENVIADA         NO REEMPLAZADA
24  4650925  032050000997692            ENVIADA         NO REEMPLAZADA
25  4650925  032050000997769            ENVIADA         NO REEMPLAZADA
26  4650925  032050000997778            ENVIADA         NO REEMPLAZADA
27  4650925  032050000997782         NO ENVIADA            REEMPLAZADA
28  4650925  032050000998042            ENVIADA         NO REEMPLAZADA
29  4650925  032050000998187            ENVIADA         NO REEMPLAZADA
30  4650925  032050000998318            ENVIADA         NO REEMPLAZADA
31  4650925  032050001090000         NO ENVIADA            REEMPLAZADA
32  4650925  032050001090051         NO ENVIADA            REEMPLAZADA
33  4650925  032050001133668            ENVIADA         NO REEMPLAZADA
34  4650925  032050001133674            ENVIADA         NO REEMPLAZADA

In [38]:
# Aplicar la nueva lógica para 'RETORNADAS AL ORIGEN'
df_caravanas_estados_consolidado.loc[
    (df_caravanas_estados_consolidado['Estado_Desde_Envio'] == 'ENVIADA') &
    (df_caravanas_estados_consolidado['Estado_Desde_Recepcion'] == 'NO RECIBIDA'),
    'Estado_Desde_Recepcion'
] = 'RETORNADAS AL ORIGEN'

print("Valores actualizados en 'Estado_Desde_Recepcion' después de aplicar la lógica de 'RETORNADAS AL ORIGEN':")
display(df_caravanas_estados_consolidado['Estado_Desde_Recepcion'].value_counts())

print("Primeros 10 registros del DataFrame consolidado con el estado actualizado:")
display(df_caravanas_estados_consolidado.sort_values(by=['ID', 'Caravana_ID']).head(50))

Valores actualizados en 'Estado_Desde_Recepcion' después de aplicar la lógica de 'RETORNADAS AL ORIGEN':

Estado_Desde_Recepcion
NO REEMPLAZADA          27
RETORNADAS AL ORIGEN     5
REEMPLAZADA              3
Name: count, dtype: int64

Primeros 10 registros del DataFrame consolidado con el estado actualizado:

         ID      Caravana_ID Estado_Desde_Envio Estado_Desde_Recepcion
0   4650925  032050000776565            ENVIADA         NO REEMPLAZADA
1   4650925  032050000776566            ENVIADA         NO REEMPLAZADA
2   4650925  032050000776567            ENVIADA   RETORNADAS AL ORIGEN
3   4650925  032050000776568            ENVIADA         NO REEMPLAZADA
4   4650925  032050000776570            ENVIADA         NO REEMPLAZADA
5   4650925  032050000776574            ENVIADA         NO REEMPLAZADA
6   4650925  032050000776575            ENVIADA   RETORNADAS AL ORIGEN
7   4650925  032050000776576            ENVIADA         NO REEMPLAZADA
8   4650925  032050000776579            ENVIADA         NO REEMPLAZADA
9   4650925  032050000997284            ENVIADA         NO REEMPLAZADA
10  4650925  032050000997328            ENVIADA         NO REEMPLAZADA
11  4650925  032050000997388            ENVIADA         NO REEMPLAZADA
12  4650925  032050000997420            ENVIADA         NO REEMPLAZADA
13  4650925  032050000997544            ENVIADA   RETORNADAS AL ORIGEN
14  4650925  032050000997546            ENVIADA   RETORNADAS AL ORIGEN
15  4650925  032050000997548            ENVIADA         NO REEMPLAZADA
16  4650925  032050000997549            ENVIADA         NO REEMPLAZADA
17  4650925  032050000997599            ENVIADA   RETORNADAS AL ORIGEN
18  4650925  032050000997601            ENVIADA         NO REEMPLAZADA
19  4650925  032050000997618            ENVIADA         NO REEMPLAZADA
20  4650925  032050000997621            ENVIADA         NO REEMPLAZADA
21  4650925  032050000997656            ENVIADA         NO REEMPLAZADA
22  4650925  032050000997659            ENVIADA         NO REEMPLAZADA
23  4650925  032050000997688            ENVIADA         NO REEMPLAZADA
24  4650925  032050000997692            ENVIADA         NO REEMPLAZADA
25  4650925  032050000997769            ENVIADA         NO REEMPLAZADA
26  4650925  032050000997778            ENVIADA         NO REEMPLAZADA
27  4650925  032050000997782         NO ENVIADA            REEMPLAZADA
28  4650925  032050000998042            ENVIADA         NO REEMPLAZADA
29  4650925  032050000998187            ENVIADA         NO REEMPLAZADA
30  4650925  032050000998318            ENVIADA         NO REEMPLAZADA
31  4650925  032050001090000         NO ENVIADA            REEMPLAZADA
32  4650925  032050001090051         NO ENVIADA            REEMPLAZADA
33  4650925  032050001133668            ENVIADA         NO REEMPLAZADA
34  4650925  032050001133674            ENVIADA         NO REEMPLAZADA

### Resumen y Próximos Pasos

Hemos llegado a un punto donde hemos consolidado el estado de cada caravana individual, permitiendo una visión detallada de las discrepancias. El DataFrame `df_caravanas_estados_consolidado` nos proporciona dos perspectivas de estado para cada `Caravana_ID`:

- **Estado_Desde_Envio**: Refleja si la caravana que se esperaba enviar fue 'RECIBIDAS', 'NO RECIBIDAS' o 'NO ENVIADA'.
- **Estado_Desde_Recepcion**: Indica si la caravana que se recibió fue 'REEMPLAZADA', 'NO REEMPLAZADA' o 'NO RECIBIDA EN CONTEO'.

Ahora, podemos realizar análisis más profundos:

#### 1. Conteo de Caravanas por Estado

In [21]:
# Contar la cantidad de caravanas por cada 'Estado_Desde_Envio'
print("Conteo de 'Estado_Desde_Envio':")
display(df_caravanas_estados_consolidado['Estado_Desde_Envio'].value_counts())

# Contar la cantidad de caravanas por cada 'Estado_Desde_Recepcion'
print("\nConteo de 'Estado_Desde_Recepcion':")
display(df_caravanas_estados_consolidado['Estado_Desde_Recepcion'].value_counts())

Conteo de 'Estado_Desde_Envio':

Estado_Desde_Envio
RECIBIDAS       27
NO RECIBIDAS     5
NO ENVIADA       3
Name: count, dtype: int64

Conteo de 'Estado_Desde_Recepcion':

Estado_Desde_Recepcion
NO REEMPLAZADA           27
NO RECIBIDA EN CONTEO     5
REEMPLAZADA               3
Name: count, dtype: int64

#### 5. Exportar los resultados

In [34]:
# Exportar el DataFrame consolidado a un archivo CSV
df_caravanas_estados_consolidado.to_csv('caravanas_estados_consolidado.csv', index=False)
print("DataFrame 'df_caravanas_estados_consolidado' exportado a 'caravanas_estados_consolidado.csv'")

# Exportar el DataFrame consolidado a un archivo XLSX
df_caravanas_estados_consolidado.to_excel('caravanas_estados_consolidado.xlsx', index=False, engine='openpyxl')
print("DataFrame 'df_caravanas_estados_consolidado' exportado a 'caravanas_estados_consolidado.xlsx'")

DataFrame 'df_caravanas_estados_consolidado' exportado a 'caravanas_estados_consolidado.csv'
DataFrame 'df_caravanas_estados_consolidado' exportado a 'caravanas_estados_consolidado.xlsx'

In [22]:
# Exportar el DataFrame consolidado a un archivo CSV
df_caravanas_estados_consolidado.to_csv('caravanas_estados_consolidado.csv', index=False)
print("DataFrame 'df_caravanas_estados_consolidado' exportado a 'caravanas_estados_consolidado.csv'")

DataFrame 'df_caravanas_estados_consolidado' exportado a 'caravanas_estados_consolidado.csv'

Para exportar a archivos `.xls` (formato Excel antiguo), necesitamos instalar la librería `xlwt`.

Para exportar a archivos `.xlsx` (formato Excel moderno), necesitamos instalar la librería `openpyxl`.

In [25]:
# Instalar la librería openpyxl
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [41]:
# Ahora intentamos exportar a .xlsx con el motor 'openpyxl'
df_caravanas_estados_consolidado.to_excel('caravanas_estados_consolidado.xlsx', index=False, engine='openpyxl')
print("DataFrame 'df_caravanas_estados_consolidado' exportado a 'caravanas_estados_consolidadov2.xlsx'")

DataFrame 'df_caravanas_estados_consolidado' exportado a 'caravanas_estados_consolidadov2.xlsx'

In [42]:
# Exportar el DataFrame consolidado a un nuevo archivo CSV
df_caravanas_estados_consolidado.to_csv('caravanas_estados_consolidado_v2.csv', index=False)
print("DataFrame 'df_caravanas_estados_consolidado' exportado a 'caravanas_estados_consolidado_v2.csv'")

# Exportar el DataFrame consolidado a un nuevo archivo XLSX
df_caravanas_estados_consolidado.to_excel('caravanas_estados_consolidado_v3.xlsx', index=False, engine='openpyxl')
print("DataFrame 'df_caravanas_estados_consolidado' exportado a 'caravanas_estados_consolidado_v3.xlsx'")

DataFrame 'df_caravanas_estados_consolidado' exportado a 'caravanas_estados_consolidado_v2.csv'
DataFrame 'df_caravanas_estados_consolidado' exportado a 'caravanas_estados_consolidado_v3.xlsx'